version: '3.4'

services:
  ta.api:
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000 # Application listens on port 8081 within the container
    ports:
       - "5000:5000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ta.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080 # Application listens on port 8080 within the container
      - ASPNETCORE_HTTPS_PORTS=8081 # Application listens on port 8081 within the container
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=123456789
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
    ports:
       - "6000:8080"
       - "6001:8081"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
