version: '3.4'

services:
  ta.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    #Not working - ASPNETCORE_ENVIRONMENT=Production
    #ASPNETCORE_URLS=https://+:5001;http://+:5000
    # ports:
    #   - "5000:5000"
    #   - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro