version: '3.4'


volumes:
  app-data:  # Define the shared volume

networks:
    postgres-db-network:
        driver: bridge

services:

  ta.api:
    image: ${DOCKER_REGISTRY-}infrastructurehost
    container_name: ta-api
    depends_on:
     postgresql.api:
        condition: service_healthy
    build:
      context: .
      dockerfile: TechnicalAnalysis.Infrastructure.Host/Dockerfile
    user: root
    ports:
      - 5000:5000
      #Remove comment to enable https - 5001:5001
    environment:
     DB_CONNECTION_STRING: "Host=postgresql.api;Port=5432;Database=TechnicalAnalysis;Username=postgres;Password=admin"
    networks:
      - postgres-db-network
# Be careful and use same path in other pc
    volumes:
      - ./TechnicalAnalysis.Infrastructure.Host/appsettings.prod.json:/app/appsettings.prod.json
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health && curl -f https://localhost:5001/health || exit 1"] #
      interval: 10s
      timeout: 5s
      retries: 3

  redis.api:
    image: redis
    container_name: ta-redis
    restart: always
    ports:
     - "6379:6379"
    environment:
     - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - postgres-db-network

  rabbitmq:
    image: rabbitmq:management
    container_name: ta-rmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - postgres-db-network

  postgresql.api:
    image: postgres:latest
    container_name: ta-postgresql
    restart: always
    ports:
     - "5432:5432"
    environment:
      POSTGRES_DB: "TechnicalAnalysis"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes: 
       - ./postgres-data:/var/lib/postgresql/data
       # copy the sql script to create tables
       - ../TechnicalAnalysis/createTables.sql:/docker-entrypoint-initdb.d/createTables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
       - postgres-db-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: ta-pgadmin
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
        PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
        - 16543:80
    networks:
        - postgres-db-network

  seq:
    container_name: ta-seq
    image: datalust/seq:latest
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y 
    networks:
      - postgres-db-network